---
apiVersion: v2
name: alfresco-content-services
version: 5.4.0-SNAPSHOT
appVersion: 7.4.0-M2
description: A Helm chart for deploying Alfresco Content Services

sources:
  - https://github.com/Alfresco/acs-deployment
dependencies:
  - name: alfresco-common
    version: 1.0.0
    repository: https://alfresco.github.io/alfresco-helm-charts/
  - name: postgresql
    version: 10.16.2
    repository: >-
      https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
    condition: postgresql.enabled
  - name: postgresql
    version: 10.16.2
    repository: >-
      https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
    alias: postgresql-syncservice
    condition: postgresql-syncservice.enabled
  - name: common
    alias: alfresco-admin-app
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.7.0
    condition: >-
      alfresco-admin-app.enabled
  - name: common
    alias: alfresco-digital-workspace
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.7.0
    condition: >-
      alfresco-digital-workspace.enabled
  # - name: activemq
  #   version: 1.1.1
  #   condition: activemq.enabled
  # - name: alfresco-search
  #   version: 1.2.0-SNAPSHOT
  #   condition: alfresco-search.enabled
  # - name: alfresco-elasticsearch-connector
  #   version: 0.3.0-SNAPSHOT
  #   condition: alfresco-elasticsearch-connector.enabled
  # - name: alfresco-sync-service
  #   version: 3.2.0-SNAPSHOT
  # - name: elasticsearch
  #   alias: elasticsearch
  #   repository: https://helm.elastic.co
  #   version: 7.10.1
  #   condition: elasticsearch.enabled
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4