alfresco-content-services:
  enabled: false
  repository:
    edition: Community
    replicaCount: 1
    strategy:
      type: Recreate
    image:
      repository: alfresco/alfresco-content-repository-community
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce

  pdfrenderer:
    replicaCount: 1

  imagemagick:
    replicaCount: 1

  libreoffice:
    replicaCount: 1

  tika:
    replicaCount: 1

  transformmisc:
    replicaCount: 1

  share:
    replicaCount: 1
    image:
      repository: alfresco/alfresco-share
    command: |
      - "bash"
      - "-c"
      - "/scripts/run.bash"
    extraVolumeMounts:
      - name: scripts
        mountPath: /scripts
        readOnly: true
    extraVolumes:
      - name: scripts
        configMap:
          name: start-script-cm
          defaultMode: 0744

  alfresco-search:
    searchServicesImage:
      repository: alfresco/alfresco-search-services
  activemq:
    enabled: true
    strategy:
      type: Recreate
  # Disable features
  alfresco-admin-app:
    enabled: false
  alfresco-digital-workspace:
    enabled: false
  alfresco-sync-service:
    syncservice:
      enabled: false
  postgresql-syncservice:
    enabled: false
  ai:
    enabled: false
  s3connector:
    enabled: false
  email:
    server:
      enabled: false
    inbound:
      enabled: false
  imap:
    server:
      enabled: false
