alfresco-content-services:
  enabled: true
  repository:
    edition: Community
    replicaCount: 1
    strategy:
      type: Recreate
    image:
      repository: alfresco/alfresco-content-repository-community
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
    ingress:
      enabled: false
  pdfrenderer:
    replicaCount: 1

  imagemagick:
    replicaCount: 1

  libreoffice:
    replicaCount: 1

  tika:
    replicaCount: 1

  transformmisc:
    replicaCount: 1

  share:
    replicaCount: 1
    image:
      repository: alfresco/alfresco-share
    ingress:
      enabled: false

  alfresco-search:
    searchServicesImage:
      repository: alfresco/alfresco-search-services
  activemq:
    enabled: true
    strategy:
      type: Recreate
  # Disable features
  alfresco-admin-app:
    enabled: false
  alfresco-digital-workspace:
    enabled: false
  alfresco-sync-service:
    syncservice:
      enabled: false
  postgresql-syncservice:
    enabled: false
  ai:
    enabled: false
  s3connector:
    enabled: false
  email:
    server:
      enabled: false
    inbound:
      enabled: false
  imap:
    server:
      enabled: false
