
alfresco-content-services:

  repository:
    edition: Community
    replicaCount: 1
    image:
      repository: alfresco/alfresco-content-repository-community

  pdfrenderer:
    replicaCount: 1

  imagemagick:
    replicaCount: 1

  libreoffice:
    replicaCount: 1

  tika:
    replicaCount: 1

  transformmisc:
    replicaCount: 1
    
  share:
    replicaCount: 1
    image:
      repository: alfresco/alfresco-share

  alfresco-search:
    searchServicesImage:
      repository: alfresco/alfresco-search-services

# Disable features
  alfresco-digital-workspace:
    enabled: false
  alfresco-sync-service:
    syncservice:
      enabled : false
  postgresql-syncservice:
    enabled: false
  ai:
    enabled: false
  s3connector:
    enabled: false
  email:
    server:
      enabled: false
    inbound:
      enabled: false
  imap:
    server:
      enabled: false