apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    argocd.argoproj.io/instance: alfresco-dev
  name: active-mq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
