apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alfresco-share-root-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "alfrescoShare"
    nginx.ingress.kubernetes.io/session-cookie-path: "/share"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "604800"
    nginx.ingress.kubernetes.io/session-cookie-expires: "604800"
    nginx.ingress.kubernetes.io/rewrite-target: /share
spec:
  ingressClassName: iap-nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: alfresco-{{ .Values.env }}-alfresco-cs-share
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.domain }}