apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alfresco-share-root-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /share
spec:
  ingressClassName: iap-nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: alfresco-{{ .Values.env }}-alfresco-cs-share
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.domain }}