apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: alfresco-dev-s3-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: alfresco-dev-s3-secret # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "ACCESSKEY"
      remoteRef:
        key: nap-alfresco-dev-secret
        version: latest
        property: ACCESSKEY

    - secretKey: "SECRETKEY"
      remoteRef:
        key: nap-alfresco-dev-secret
        version: latest
        property: SECRETKEY


